#!/bin/bash

help() {
	printf "%b\n" "\033[1;36mtermheight\033[0m"\
		"Customize the scroll margin of your terminal!"\
		"termsize help"\
		"	Shows this help text"\
		""\
		"termsize reset"\
		"	Resets terminal scroll margin to default"\
		""\
		"termsize <height>"\
		"	Sets terminal scroll margin to provided value"\
		""
	exit
}

# core function
resize() {
	local height=$1
	printf "\033[1;${height}r"
}

shopt -s extglob
arg="$1"
case "$arg" in
	reset*)
		resize;;
	+([0-9]))
		resize $arg;;
	*)
		help;;
esac
